import { IconProp } from '@fortawesome/fontawesome-svg-core';
import {
  faAlbum,
  faAlbumCirclePlus,
  faAlbumCircleUser,
  faAngle,
  faAngle90,
  faArrowUpFromGroundWater,
  faAtom,
  faAtomSimple,
  faBallPile,
  faBanBug,
  faBarcode,
  faBars,
  faBarsFilter,
  faBarsSort,
  faBarsStaggered,
  faBath,
  faBatteryBolt,
  faBatteryEmpty,
  faBatteryExclamation,
  faBatteryFull,
  faBatteryHalf,
  faBatteryLow,
  faBatteryQuarter,
  faBatterySlash,
  faBatteryThreeQuarters,
  faBezierCurve,
  faBinary,
  faBinaryCircleCheck,
  faBinaryLock,
  faBinarySlash,
  faBiohazard,
  faBlenderPhone,
  faBluetooth,
  faBolt,
  faBookFont,
  faBookSparkles,
  faBoxArchive,
  faBracketCurly,
  faBracketCurlyRight,
  faBracketRound,
  faBracketRoundRight,
  faBracketSquare,
  faBracketSquareRight,
  faBracketsCurly,
  faBracketsRound,
  faBracketsSquare,
  faBrain,
  faBrainCircuit,
  faBrakeWarning,
  faBringForward,
  faBringFront,
  faBrowser,
  faBrowsers,
  faBrush,
  faBug,
  faBugSlash,
  faBurrito,
  faBus,
  faBusSimple,
  faCamera,
  faCameraPolaroid,
  faCameraRetro,
  faCameraWeb,
  faCameraWebSlash,
  faCapsules,
  faCar,
  faCarBattery,
  faCarBolt,
  faCarBuilding,
  faCarBump,
  faCarBurst,
  faCarBus,
  faCarCircleBolt,
  faCarGarage,
  faCarMirrors,
  faCarOn,
  faCarRear,
  faCarSide,
  faCarSideBolt,
  faCarTilt,
  faCarTunnel,
  faCarWash,
  faCarWrench,
  faCaravan,
  faCaravanSimple,
  faCars,
  faCauldron,
  faChargingStation,
  faChartMixed,
  faChartNetwork,
  faChartScatter,
  faCircleDashed,
  faCircleHalfStroke,
  faCircleNodes,
  faCircleRadiation,
  faClipboardCheck,
  faClone,
  faCloud,
  faCloudArrowDown,
  faCloudArrowUp,
  faCloudCheck,
  faCloudExclamation,
  faCloudMinus,
  faCloudPlus,
  faCloudQuestion,
  faCloudSlash,
  faCloudXmark,
  faCode,
  faCodeBranch,
  faCodeCommit,
  faCodeCompare,
  faCodeFork,
  faCodeMerge,
  faCodePullRequest,
  faCodePullRequestClosed,
  faCodePullRequestDraft,
  faCodeSimple,
  faColumns3,
  faCompactDisc,
  faCompassDrafting,
  faComputer,
  faComputerClassic,
  faComputerMouse,
  faComputerMouseScrollwheel,
  faComputerSpeaker,
  faCopy,
  faCrop,
  faCropSimple,
  faCrosshairs,
  faCrosshairsSimple,
  faCube,
  faCubes,
  faDatabase,
  faDesktop,
  faDesktopArrowDown,
  faDiagramProject,
  faDiscDrive,
  faDisease,
  faDisplay,
  faDisplayArrowDown,
  faDisplayCode,
  faDisplayMedical,
  faDisplaySlash,
  faDistributeSpacingHorizontal,
  faDistributeSpacingVertical,
  faDna,
  faDownload,
  faDrawCircle,
  faDrawPolygon,
  faDrawSquare,
  faDroplet,
  faDropletSlash,
  faEngine,
  faEngineWarning,
  faEraser,
  faEthernet,
  faExplosion,
  faEye,
  faEyeDropper,
  faEyeDropperFull,
  faEyeDropperHalf,
  faEyeSlash,
  faFan,
  faFax,
  faFile,
  faFileCode,
  faFileLines,
  faFill,
  faFillDrip,
  faFilter,
  faFire,
  faFireExtinguisher,
  faFireFlameCurved,
  faFireFlameSimple,
  faFlashlight,
  faFlask,
  faFlaskRoundPoison,
  faFlaskRoundPotion,
  faFlaskVial,
  faFloppyDiskPen,
  faFloppyDisks,
  faFluxCapacitor,
  faFolder,
  faFolderOpen,
  faFontAwesome,
  faFrame,
  faFrog,
  faGalleryThumbnails,
  faGameConsoleHandheld,
  faGamepad,
  faGamepadModern,
  faGarage,
  faGarageCar,
  faGarageOpen,
  faGasPump,
  faGasPumpSlash,
  faGauge,
  faGaugeCircleBolt,
  faGaugeCircleMinus,
  faGaugeCirclePlus,
  faGaugeHigh,
  faGaugeLow,
  faGaugeMax,
  faGaugeMin,
  faGaugeSimple,
  faGaugeSimpleHigh,
  faGaugeSimpleLow,
  faGaugeSimpleMax,
  faGaugeSimpleMin,
  faGears,
  faGlobe,
  faGrate,
  faGrateDroplet,
  faGrid,
  faGrid2,
  faGrid2Plus,
  faGrid4,
  faGrid5,
  faGridDividers,
  faHardDrive,
  faHeadSideBrain,
  faHeadphones,
  faHeat,
  faHighlighter,
  faHighlighterLine,
  faHouseDay,
  faHouseLaptop,
  faHouseNight,
  faHouseSignal,
  faIcons,
  faImagePolaroid,
  faIndustry,
  faIndustryWindows,
  faKeySkeleton,
  faKeySkeletonLeftRight,
  faKeyboard,
  faKeyboardDown,
  faKeyboardLeft,
  faKite,
  faLampStreet,
  faLaptop,
  faLaptopArrowDown,
  faLaptopCode,
  faLaptopFile,
  faLaptopMobile,
  faLaptopSlash,
  faLasso,
  faLassoSparkles,
  faLayerGroup,
  faLayerMinus,
  faLayerPlus,
  faLeaf,
  faLightbulb,
  faLightbulbCfl,
  faLinesLeaning,
  faLinkHorizontal,
  faLinkHorizontalSlash,
  faMagnet,
  faManhole,
  faMarker,
  faMemory,
  faMerge,
  faMeter,
  faMeterBolt,
  faMeterDroplet,
  faMeterFire,
  faMicrochip,
  faMicrochipAi,
  faMicroscope,
  faMobile,
  faMobileButton,
  faMobileNotch,
  faMobileRetro,
  faMobileScreen,
  faMobileScreenButton,
  faMobileSignal,
  faMobileSignalOut,
  faMoped,
  faMortarPestle,
  faMotorcycle,
  faMp3Player,
  faMugSaucer,
  faNetworkWired,
  faNfcSignal,
  faNotdef,
  faNotebook,
  faObjectExclude,
  faObjectGroup,
  faObjectIntersect,
  faObjectSubtract,
  faObjectUngroup,
  faObjectUnion,
  faObjectsAlignBottom,
  faObjectsAlignCenterHorizontal,
  faObjectsAlignCenterVertical,
  faObjectsAlignLeft,
  faObjectsAlignRight,
  faObjectsAlignTop,
  faObjectsColumn,
  faOctagonExclamation,
  faOilCan,
  faOilCanDrip,
  faOilTemperature,
  faOilWell,
  faOutlet,
  faPaintRoller,
  faPaintbrush,
  faPaintbrushFine,
  faPaintbrushPencil,
  faPalette,
  faPaste,
  faPedestal,
  faPen,
  faPenCircle,
  faPenClip,
  faPenFancy,
  faPenNib,
  faPenNibSlash,
  faPenRuler,
  faPenToSquare,
  faPencil,
  faPhoneOffice,
  faPills,
  faPipeCircleCheck,
  faPipeCollar,
  faPipeSection,
  faPipeValve,
  faPlug,
  faPlugCircleBolt,
  faPlugCircleCheck,
  faPlugCircleExclamation,
  faPlugCircleMinus,
  faPlugCirclePlus,
  faPlugCircleXmark,
  faPoop,
  faPowerOff,
  faPrescriptionBottle,
  faPrint,
  faProjector,
  faPump,
  faQrcode,
  faRadiation,
  faRectangleCode,
  faRectanglePro,
  faRectangleTerminal,
  faRectangleXmark,
  faRectanglesMixed,
  faRouter,
  faRss,
  faRulerCombined,
  faRulerHorizontal,
  faRulerVertical,
  faRv,
  faSatellite,
  faSatelliteDish,
  faScannerImage,
  faScissors,
  faScribble,
  faSdCard,
  faSdCards,
  faSeedling,
  faSendBack,
  faSendBackward,
  faServer,
  faShield,
  faShieldCheck,
  faShieldHalved,
  faShredder,
  faSidebar,
  faSidebarFlip,
  faSignal,
  faSignalBars,
  faSignalBarsFair,
  faSignalBarsGood,
  faSignalBarsSlash,
  faSignalBarsWeak,
  faSignalFair,
  faSignalGood,
  faSignalSlash,
  faSignalStream,
  faSignalStreamSlash,
  faSignalStrong,
  faSignalWeak,
  faSimCard,
  faSimCards,
  faSitemap,
  faSkullCrossbones,
  faSolarPanel,
  faSpeaker,
  faSpeakers,
  faSplit,
  faSplotch,
  faSprayCan,
  faSprayCanSparkles,
  faSquareCode,
  faSquareDashed,
  faSquareTerminal,
  faSquareVirus,
  faStamp,
  faStapler,
  faSteeringWheel,
  faSun,
  faSwatchbook,
  faSymbols,
  faSyringe,
  faTablet,
  faTabletButton,
  faTabletScreen,
  faTabletScreenButton,
  faTablets,
  faTachographDigital,
  faTally,
  faTankWater,
  faTaxi,
  faTemperatureHigh,
  faTemperatureLow,
  faTerminal,
  faTire,
  faTireFlat,
  faTirePressureWarning,
  faTireRugged,
  faTowerBroadcast,
  faTowerCell,
  faTrailer,
  faTransformerBolt,
  faTruck,
  faTruckBolt,
  faTruckField,
  faTruckFieldUn,
  faTruckMedical,
  faTruckMonster,
  faTruckPickup,
  faTv,
  faTvMusic,
  faTvRetro,
  faTypewriter,
  faUpload,
  faUsbDrive,
  faUserSecret,
  faUtilityPole,
  faUtilityPoleDouble,
  faVanShuttle,
  faVectorCircle,
  faVectorPolygon,
  faVectorSquare,
  faVentDamper,
  faVial,
  faVialCircleCheck,
  faVialVirus,
  faVials,
  faWagonCovered,
  faWalkieTalkie,
  faWandMagic,
  faWandMagicSparkles,
  faWatchCalculator,
  faWater,
  faWifi,
  faWifiExclamation,
  faWifiFair,
  faWifiWeak,
  faWind,
  faWindTurbine,
  faWindow,
  faWindowFlip,
  faWindowMaximize,
  faWindowMinimize,
  faWindowRestore,
  faWrenchSimple,
} from '@fortawesome/pro-regular-svg-icons';

export const courseIcons: Record<string, IconProp> = {
  faBars: faBars,
  faShieldHalved: faShieldHalved,
  faFile: faFile,
  faFilter: faFilter,
  faBarcode: faBarcode,
  faFolder: faFolder,
  faFolderOpen: faFolderOpen,
  faGears: faGears,
  faCode: faCode,
  faWindow: faWindow,
  faBath: faBath,
  faBracketsCurly: faBracketsCurly,
  faBug: faBug,
  faMugSaucer: faMugSaucer,
  faCodeCompare: faCodeCompare,
  faUserSecret: faUserSecret,
  faBrowser: faBrowser,
  faNetworkWired: faNetworkWired,
  faShield: faShield,
  faShieldCheck: faShieldCheck,
  faSitemap: faSitemap,
  faCodeBranch: faCodeBranch,
  faWindowRestore: faWindowRestore,
  faWindowMinimize: faWindowMinimize,
  faWindowMaximize: faWindowMaximize,
  faWindowFlip: faWindowFlip,
  faTerminal: faTerminal,
  faSquareTerminal: faSquareTerminal,
  faSquareCode: faSquareCode,
  faSplit: faSplit,
  faSidebarFlip: faSidebarFlip,
  faSidebar: faSidebar,
  faRectangleXmark: faRectangleXmark,
  faRectangleTerminal: faRectangleTerminal,
  faRectangleCode: faRectangleCode,
  faQrcode: faQrcode,
  faOctagonExclamation: faOctagonExclamation,
  faNotdef: faNotdef,
  faMerge: faMerge,
  faLaptopCode: faLaptopCode,
  faKeySkeletonLeftRight: faKeySkeletonLeftRight,
  faFireExtinguisher: faFireExtinguisher,
  faFileLines: faFileLines,
  faFileCode: faFileCode,
  faDiagramProject: faDiagramProject,
  faCodeSimple: faCodeSimple,
  faCodePullRequestDraft: faCodePullRequestDraft,
  faCodePullRequestClosed: faCodePullRequestClosed,
  faCodePullRequest: faCodePullRequest,
  faCodeMerge: faCodeMerge,
  faCodeFork: faCodeFork,
  faCodeCommit: faCodeCommit,
  faBugSlash: faBugSlash,
  faBrowsers: faBrowsers,
  faBrainCircuit: faBrainCircuit,
  faBracketsSquare: faBracketsSquare,
  faBracketsRound: faBracketsRound,
  faBracketSquareRight: faBracketSquareRight,
  faBracketSquare: faBracketSquare,
  faBracketRoundRight: faBracketRoundRight,
  faBracketRound: faBracketRound,
  faBracketCurlyRight: faBracketCurlyRight,
  faBracketCurly: faBracketCurly,
  faBoxArchive: faBoxArchive,
  faBinarySlash: faBinarySlash,
  faBinaryLock: faBinaryLock,
  faBinaryCircleCheck: faBinaryCircleCheck,
  faBinary: faBinary,
  faBarsStaggered: faBarsStaggered,
  faBarsSort: faBarsSort,
  faBarsFilter: faBarsFilter,
  faBanBug: faBanBug,
  faCloud: faCloud,
  faGlobe: faGlobe,
  faWifi: faWifi,
  faCloudArrowUp: faCloudArrowUp,
  faSignalBars: faSignalBars,
  faSignalSlash: faSignalSlash,
  faSignal: faSignal,
  faWifiWeak: faWifiWeak,
  faWifiFair: faWifiFair,
  faWifiExclamation: faWifiExclamation,
  faTowerCell: faTowerCell,
  faTowerBroadcast: faTowerBroadcast,
  faSignalWeak: faSignalWeak,
  faSignalStrong: faSignalStrong,
  faSignalStreamSlash: faSignalStreamSlash,
  faSignalStream: faSignalStream,
  faSignalGood: faSignalGood,
  faSignalFair: faSignalFair,
  faSignalBarsWeak: faSignalBarsWeak,
  faSignalBarsSlash: faSignalBarsSlash,
  faSignalBarsGood: faSignalBarsGood,
  faSignalBarsFair: faSignalBarsFair,
  faRss: faRss,
  faNfcSignal: faNfcSignal,
  faLinkHorizontalSlash: faLinkHorizontalSlash,
  faLinkHorizontal: faLinkHorizontal,
  faHouseSignal: faHouseSignal,
  faCloudXmark: faCloudXmark,
  faCloudSlash: faCloudSlash,
  faCloudQuestion: faCloudQuestion,
  faCloudPlus: faCloudPlus,
  faCloudMinus: faCloudMinus,
  faCloudExclamation: faCloudExclamation,
  faCloudCheck: faCloudCheck,
  faCloudArrowDown: faCloudArrowDown,
  faBluetooth: faBluetooth,
  faCar: faCar,
  faTruck: faTruck,
  faGauge: faGauge,
  faCarSide: faCarSide,
  faMoped: faMoped,
  faCarBuilding: faCarBuilding,
  faMotorcycle: faMotorcycle,
  faTruckMonster: faTruckMonster,
  faWagonCovered: faWagonCovered,
  faEngineWarning: faEngineWarning,
  faVanShuttle: faVanShuttle,
  faTruckPickup: faTruckPickup,
  faTruckMedical: faTruckMedical,
  faTruckFieldUn: faTruckFieldUn,
  faTruckField: faTruckField,
  faTruckBolt: faTruckBolt,
  faTrailer: faTrailer,
  faTireRugged: faTireRugged,
  faTirePressureWarning: faTirePressureWarning,
  faTireFlat: faTireFlat,
  faTire: faTire,
  faTaxi: faTaxi,
  faTankWater: faTankWater,
  faSteeringWheel: faSteeringWheel,
  faSprayCanSparkles: faSprayCanSparkles,
  faRv: faRv,
  faPump: faPump,
  faOilTemperature: faOilTemperature,
  faOilCanDrip: faOilCanDrip,
  faOilCan: faOilCan,
  faGaugeSimpleMin: faGaugeSimpleMin,
  faGaugeSimpleMax: faGaugeSimpleMax,
  faGaugeSimpleLow: faGaugeSimpleLow,
  faGaugeSimpleHigh: faGaugeSimpleHigh,
  faGaugeSimple: faGaugeSimple,
  faGaugeMin: faGaugeMin,
  faGaugeMax: faGaugeMax,
  faGaugeLow: faGaugeLow,
  faGaugeHigh: faGaugeHigh,
  faGaugeCirclePlus: faGaugeCirclePlus,
  faGaugeCircleMinus: faGaugeCircleMinus,
  faGaugeCircleBolt: faGaugeCircleBolt,
  faGasPumpSlash: faGasPumpSlash,
  faGasPump: faGasPump,
  faGarageOpen: faGarageOpen,
  faGarageCar: faGarageCar,
  faGarage: faGarage,
  faEngine: faEngine,
  faChargingStation: faChargingStation,
  faCars: faCars,
  faCaravanSimple: faCaravanSimple,
  faCaravan: faCaravan,
  faCarWrench: faCarWrench,
  faCarWash: faCarWash,
  faCarTunnel: faCarTunnel,
  faCarTilt: faCarTilt,
  faCarSideBolt: faCarSideBolt,
  faCarRear: faCarRear,
  faCarOn: faCarOn,
  faCarMirrors: faCarMirrors,
  faCarGarage: faCarGarage,
  faCarCircleBolt: faCarCircleBolt,
  faCarBus: faCarBus,
  faCarBurst: faCarBurst,
  faCarBump: faCarBump,
  faCarBolt: faCarBolt,
  faCarBattery: faCarBattery,
  faBusSimple: faBusSimple,
  faBus: faBus,
  faBrakeWarning: faBrakeWarning,
  faWandMagicSparkles: faWandMagicSparkles,
  faPenNib: faPenNib,
  faPen: faPen,
  faGrid2: faGrid2,
  faCircleHalfStroke: faCircleHalfStroke,
  faDroplet: faDroplet,
  faPenToSquare: faPenToSquare,
  faEye: faEye,
  faEyeSlash: faEyeSlash,
  faPaintRoller: faPaintRoller,
  faBrush: faBrush,
  faPalette: faPalette,
  faLayerGroup: faLayerGroup,
  faPenFancy: faPenFancy,
  faPencil: faPencil,
  faCopy: faCopy,
  faIcons: faIcons,
  faMarker: faMarker,
  faCube: faCube,
  faCrosshairs: faCrosshairs,
  faClone: faClone,
  faEraser: faEraser,
  faRulerVertical: faRulerVertical,
  faDrawSquare: faDrawSquare,
  faStamp: faStamp,
  faWrenchSimple: faWrenchSimple,
  faWandMagic: faWandMagic,
  faVectorSquare: faVectorSquare,
  faVectorPolygon: faVectorPolygon,
  faVectorCircle: faVectorCircle,
  faSymbols: faSymbols,
  faSwatchbook: faSwatchbook,
  faStapler: faStapler,
  faSquareDashed: faSquareDashed,
  faSprayCan: faSprayCan,
  faSplotch: faSplotch,
  faSendBackward: faSendBackward,
  faSendBack: faSendBack,
  faScribble: faScribble,
  faScissors: faScissors,
  faRulerHorizontal: faRulerHorizontal,
  faRulerCombined: faRulerCombined,
  faRectanglesMixed: faRectanglesMixed,
  faRectanglePro: faRectanglePro,
  faPenRuler: faPenRuler,
  faPenNibSlash: faPenNibSlash,
  faPenClip: faPenClip,
  faPenCircle: faPenCircle,
  faPaste: faPaste,
  faPaintbrushPencil: faPaintbrushPencil,
  faPaintbrushFine: faPaintbrushFine,
  faPaintbrush: faPaintbrush,
  faObjectsColumn: faObjectsColumn,
  faObjectsAlignTop: faObjectsAlignTop,
  faObjectsAlignRight: faObjectsAlignRight,
  faObjectsAlignLeft: faObjectsAlignLeft,
  faObjectsAlignCenterVertical: faObjectsAlignCenterVertical,
  faObjectsAlignCenterHorizontal: faObjectsAlignCenterHorizontal,
  faObjectsAlignBottom: faObjectsAlignBottom,
  faObjectUnion: faObjectUnion,
  faObjectUngroup: faObjectUngroup,
  faObjectSubtract: faObjectSubtract,
  faObjectIntersect: faObjectIntersect,
  faObjectGroup: faObjectGroup,
  faObjectExclude: faObjectExclude,
  faNotebook: faNotebook,
  faLinesLeaning: faLinesLeaning,
  faLayerPlus: faLayerPlus,
  faLayerMinus: faLayerMinus,
  faLassoSparkles: faLassoSparkles,
  faLasso: faLasso,
  faImagePolaroid: faImagePolaroid,
  faHighlighterLine: faHighlighterLine,
  faHighlighter: faHighlighter,
  faGridDividers: faGridDividers,
  faGrid5: faGrid5,
  faGrid4: faGrid4,
  faGrid2Plus: faGrid2Plus,
  faGrid: faGrid,
  faGalleryThumbnails: faGalleryThumbnails,
  faFrame: faFrame,
  faFontAwesome: faFontAwesome,
  faFillDrip: faFillDrip,
  faFill: faFill,
  faEyeDropperHalf: faEyeDropperHalf,
  faEyeDropperFull: faEyeDropperFull,
  faEyeDropper: faEyeDropper,
  faDropletSlash: faDropletSlash,
  faDrawPolygon: faDrawPolygon,
  faDrawCircle: faDrawCircle,
  faDistributeSpacingVertical: faDistributeSpacingVertical,
  faDistributeSpacingHorizontal: faDistributeSpacingHorizontal,
  faCubes: faCubes,
  faCrosshairsSimple: faCrosshairsSimple,
  faCropSimple: faCropSimple,
  faCrop: faCrop,
  faCompassDrafting: faCompassDrafting,
  faColumns3: faColumns3,
  faCircleNodes: faCircleNodes,
  faCircleDashed: faCircleDashed,
  faCameraPolaroid: faCameraPolaroid,
  faBringFront: faBringFront,
  faBringForward: faBringForward,
  faBookFont: faBookFont,
  faBezierCurve: faBezierCurve,
  faBallPile: faBallPile,
  faAngle90: faAngle90,
  faAngle: faAngle,
  faDownload: faDownload,
  faCameraRetro: faCameraRetro,
  faHeadphones: faHeadphones,
  faPrint: faPrint,
  faCamera: faCamera,
  faGamepad: faGamepad,
  faComputerClassic: faComputerClassic,
  faUpload: faUpload,
  faComputerSpeaker: faComputerSpeaker,
  faDatabase: faDatabase,
  faMobile: faMobile,
  faServer: faServer,
  faLaptop: faLaptop,
  faPhoneOffice: faPhoneOffice,
  faProjector: faProjector,
  faPowerOff: faPowerOff,
  faDesktop: faDesktop,
  faWalkieTalkie: faWalkieTalkie,
  faTypewriter: faTypewriter,
  faComputerMouseScrollwheel: faComputerMouseScrollwheel,
  faMicrochip: faMicrochip,
  faSpeaker: faSpeaker,
  faSpeakers: faSpeakers,
  faAlbum: faAlbum,
  faPlug: faPlug,
  faKeyboard: faKeyboard,
  faTablet: faTablet,
  faGameConsoleHandheld: faGameConsoleHandheld,
  faWatchCalculator: faWatchCalculator,
  faUsbDrive: faUsbDrive,
  faTvRetro: faTvRetro,
  faTvMusic: faTvMusic,
  faTv: faTv,
  faTachographDigital: faTachographDigital,
  faTabletScreenButton: faTabletScreenButton,
  faTabletScreen: faTabletScreen,
  faTabletButton: faTabletButton,
  faSimCards: faSimCards,
  faSimCard: faSimCard,
  faShredder: faShredder,
  faSdCards: faSdCards,
  faSdCard: faSdCard,
  faScannerImage: faScannerImage,
  faSatelliteDish: faSatelliteDish,
  faSatellite: faSatellite,
  faRouter: faRouter,
  faMp3Player: faMp3Player,
  faMobileSignalOut: faMobileSignalOut,
  faMobileSignal: faMobileSignal,
  faMobileScreenButton: faMobileScreenButton,
  faMobileScreen: faMobileScreen,
  faMobileRetro: faMobileRetro,
  faMobileNotch: faMobileNotch,
  faMobileButton: faMobileButton,
  faMicrochipAi: faMicrochipAi,
  faMeter: faMeter,
  faMemory: faMemory,
  faLaptopSlash: faLaptopSlash,
  faLaptopMobile: faLaptopMobile,
  faLaptopFile: faLaptopFile,
  faLaptopArrowDown: faLaptopArrowDown,
  faKeyboardLeft: faKeyboardLeft,
  faKeyboardDown: faKeyboardDown,
  faHouseLaptop: faHouseLaptop,
  faHardDrive: faHardDrive,
  faGamepadModern: faGamepadModern,
  faFluxCapacitor: faFluxCapacitor,
  faFloppyDisks: faFloppyDisks,
  faFloppyDiskPen: faFloppyDiskPen,
  faFlashlight: faFlashlight,
  faFax: faFax,
  faEthernet: faEthernet,
  faDisplaySlash: faDisplaySlash,
  faDisplayMedical: faDisplayMedical,
  faDisplayCode: faDisplayCode,
  faDisplayArrowDown: faDisplayArrowDown,
  faDisplay: faDisplay,
  faDiscDrive: faDiscDrive,
  faDesktopArrowDown: faDesktopArrowDown,
  faComputerMouse: faComputerMouse,
  faComputer: faComputer,
  faCompactDisc: faCompactDisc,
  faCameraWebSlash: faCameraWebSlash,
  faCameraWeb: faCameraWeb,
  faBlenderPhone: faBlenderPhone,
  faAlbumCircleUser: faAlbumCircleUser,
  faAlbumCirclePlus: faAlbumCirclePlus,
  faBolt: faBolt,
  faFire: faFire,
  faSun: faSun,
  faAtomSimple: faAtomSimple,
  faBurrito: faBurrito,
  faWater: faWater,
  faLeaf: faLeaf,
  faSeedling: faSeedling,
  faHouseNight: faHouseNight,
  faWind: faWind,
  faLightbulb: faLightbulb,
  faSolarPanel: faSolarPanel,
  faIndustry: faIndustry,
  faWindTurbine: faWindTurbine,
  faVentDamper: faVentDamper,
  faUtilityPoleDouble: faUtilityPoleDouble,
  faUtilityPole: faUtilityPole,
  faTransformerBolt: faTransformerBolt,
  faRadiation: faRadiation,
  faPoop: faPoop,
  faPlugCircleXmark: faPlugCircleXmark,
  faPlugCirclePlus: faPlugCirclePlus,
  faPlugCircleMinus: faPlugCircleMinus,
  faPlugCircleExclamation: faPlugCircleExclamation,
  faPlugCircleCheck: faPlugCircleCheck,
  faPlugCircleBolt: faPlugCircleBolt,
  faPipeValve: faPipeValve,
  faPipeSection: faPipeSection,
  faPipeCollar: faPipeCollar,
  faPipeCircleCheck: faPipeCircleCheck,
  faPedestal: faPedestal,
  faOutlet: faOutlet,
  faOilWell: faOilWell,
  faMeterFire: faMeterFire,
  faMeterDroplet: faMeterDroplet,
  faMeterBolt: faMeterBolt,
  faManhole: faManhole,
  faLightbulbCfl: faLightbulbCfl,
  faLampStreet: faLampStreet,
  faIndustryWindows: faIndustryWindows,
  faHouseDay: faHouseDay,
  faHeat: faHeat,
  faGrateDroplet: faGrateDroplet,
  faGrate: faGrate,
  faFireFlameSimple: faFireFlameSimple,
  faFireFlameCurved: faFireFlameCurved,
  faFan: faFan,
  faExplosion: faExplosion,
  faCircleRadiation: faCircleRadiation,
  faBatteryThreeQuarters: faBatteryThreeQuarters,
  faBatterySlash: faBatterySlash,
  faBatteryQuarter: faBatteryQuarter,
  faBatteryLow: faBatteryLow,
  faBatteryHalf: faBatteryHalf,
  faBatteryFull: faBatteryFull,
  faBatteryExclamation: faBatteryExclamation,
  faBatteryEmpty: faBatteryEmpty,
  faBatteryBolt: faBatteryBolt,
  faAtom: faAtom,
  faArrowUpFromGroundWater: faArrowUpFromGroundWater,
  faMagnet: faMagnet,
  faFlask: faFlask,
  faChartScatter: faChartScatter,
  faTally: faTally,
  faVials: faVials,
  faBrain: faBrain,
  faCauldron: faCauldron,
  faTablets: faTablets,
  faVialVirus: faVialVirus,
  faVialCircleCheck: faVialCircleCheck,
  faVial: faVial,
  faTemperatureLow: faTemperatureLow,
  faTemperatureHigh: faTemperatureHigh,
  faSyringe: faSyringe,
  faSquareVirus: faSquareVirus,
  faSkullCrossbones: faSkullCrossbones,
  faPrescriptionBottle: faPrescriptionBottle,
  faPills: faPills,
  faMortarPestle: faMortarPestle,
  faMicroscope: faMicroscope,
  faKite: faKite,
  faKeySkeleton: faKeySkeleton,
  faHeadSideBrain: faHeadSideBrain,
  faFrog: faFrog,
  faFlaskVial: faFlaskVial,
  faFlaskRoundPotion: faFlaskRoundPotion,
  faFlaskRoundPoison: faFlaskRoundPoison,
  faDna: faDna,
  faDisease: faDisease,
  faClipboardCheck: faClipboardCheck,
  faChartNetwork: faChartNetwork,
  faChartMixed: faChartMixed,
  faCapsules: faCapsules,
  faBookSparkles: faBookSparkles,
  faBiohazard: faBiohazard,
};
