# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    ENV["ENTRY_FILE"] = "index.tsx"
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci if ENV['CI']
    #increment_build_number(xcodeproj: "students.xcodeproj")
    sync_code_signing(type: "appstore", readonly: true)
    build_app(scheme: "students",export_method: "app-store")
    # upload_to_testflight(skip_submission: true, submit_beta_review: false)
  end
end
