# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_ci if ENV['CI']
    sync_code_signing(type: "appstore", readonly: true)
  end

  lane :release do
    increment_build_number(xcodeproj: "students.xcodeproj", build_number: ENV['BUILD_NO'])
    increment_version_number(xcodeproj: "students.xcodeproj", version_number: ENV['APP_VERSION'])

    build_app(
      scheme: "students",
      export_method: "app-store",
      workspace: "students.xcworkspace",
      output_directory: "./build",
      silent: true,
    )

    upload_to_testflight(
      skip_submission: true,
      skip_waiting_for_build_processing: true,
      submit_beta_review: false,
      apple_id: "6443913305",
    )

    source_map_path = '../../main.jsbundle.map'

    begin
      sentry_upload_sourcemap(
        auth_token: ENV['SENTRY_AUTH_TOKEN'],
        org_slug: ENV['SENTRY_ORG'],
        project_slug: ENV['SENTRY_PROJECT'],
        version: 'it.polito.students@' + ENV['APP_VERSION'],
        build: ENV['BUILD_PIECE'],
        sourcemap: [source_map_path],
        rewrite: true
      )
    rescue => e
      UI.important("Sentry sourcemap upload failed => #{e.message}")
    end
  end

  lane :verify do
    build_app(
      scheme: "students",
      export_method: "app-store",
      workspace: "students.xcworkspace",
      output_directory: "./build",
      silent: true,
    )
  end
end
